sonar.projectKey=divyanshichugh4_T-AWS-lab
sonar.organization=divyanshichugh4

sonar.sources=.
sonar.terraform.provider.aws.version=6.0

sonar.exclusions=.terraform/**,**/.terraform/**,terraform.tfstate,terraform.tfstate.backup
